version: "3.5"
services:
  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: 'always'
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:

